---
- name: Install packages for managing abuse_ip blocklist with python
  ansible.builtin.pip:
    name:
      - jinja2
      - requests

- name: Move python script to lib
  ansible.builtin.template:
    src: abuseipdb/manage_nft_abuseip_blocklist.py.j2
    dest: "{{ nftables_script_folder }}/manage_nft_abuseip_blocklist.py"
    owner: root
    group: root
    mode: u=rwx,g=rx,o=x
  become: true
  when: abuseip_api_key is defined

- name: Make systemd services for update-abuseip-blocklist
  block:
    - name: Move update-abuseip-blocklist systemd timer file to host
      ansible.builtin.template:
        src: abuseipdb/update-abuseip-blocklist.timer.j2
        dest: "/lib/systemd/system/update-abuseip-blocklist.timer"
        # validate: "systemd-analyze verify %s"
        owner: root
        group: root
        mode: u=rw,g=r,o=r
      become: true

    - name: Move update-abuseip-blocklist systemd service file to host
      ansible.builtin.template:
        src: abuseipdb/update-abuseip-blocklist.service.j2
        dest: "/lib/systemd/system/update-abuseip-blocklist.service"
        # validate: "systemd-analyze verify %s"
        owner: root
        group: root
        mode: u=rw,g=r,o=r
      become: true

    - name: Validate update-abuseip-blocklist.service
      ansible.builtin.command: systemd-analyze verify update-abuseip-blocklist.service
      args:
        chdir: "/lib/systemd"
      changed_when: false
      become: true

    - name: Validate update-abuseip-blocklist.timer
      ansible.builtin.command: systemd-analyze verify update-abuseip-blocklist.timer
      args:
        chdir: "/lib/systemd"
      changed_when: false
      become: true
      notify:
        - enable abuseip-blocklist timer

- name: Create blocklist in nft as table and file
  block:
    - name: Create blocklist table when it does not exist in nft
      ansible.builtin.command: "nft add table blocklist"
      become: true
      changed_when: true
      when: not table in nft_table_names
      tags:
        - nftables_setup

    - name: Create blocklist as empty table if it does not exist in nft
      ansible.builtin.template:
        src: abuseipdb/blocklist.nft.j2
        dest: "{{ nftables_dir }}/blocklist.nft"
        mode: u=rw,g=r,o=
      # crashes on validation due to dependencies,
      # gets validated as a whole when global file is pushed
      # validate: /usr/sbin/nft -c -f %s
      become: true
      # when table just got created
      when: not "inet blocklist" in nft_table_names
      tags:
        - nftables_setup
      notify:
        - reload nftables ruleset
        - start nftables service
        - enable nftables service
