---
- name: Create nftables systemd directory
  ansible.builtin.file:
    dest: /etc/systemd/system/nftables.service.d
    state: directory
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
  become: true
  tags:
    - nftables_setup

- name: Edit nftables service to point to our main nftables file
  ansible.builtin.template:
    src: systemd/nftables.service.j2
    dest: /etc/systemd/system/nftables.service.d/override.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  when: not ansible_check_mode
  become: true
  tags:
    - nftables_setup
