---
- name: Reload nft ruleset
  ansible.builtin.command: "{{ nftables_script_folder }}/reload_firewall.sh"
  become: true
  changed_when: true
  listen: reload nftables ruleset

- name: Start nftables service
  ansible.builtin.systemd:
    name: nftables
    state: started
    daemon_reload: true
  become: true
  listen: start nftables service

- name: Enable nftables service
  ansible.builtin.systemd:
    name: nftables
    daemon_reload: true
    enabled: true
  when: nftables_enable_service
  become: true
  listen: enable nftables service
