# terraform managed
# Inspired on: https://github.com/ansible-community/molecule-plugins/blob/main/src/molecule_plugins/docker/playbooks/Dockerfile.j2

# Pull from a registry if specified in molecule.yml
{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

# Make additional Mocule env variables possible
{% if item.env is defined %}
{% for var, value in item.env.items() %}
{% if value %}
ENV {{ var }} {{ value }}
{% endif %}
{% endfor %}
{% endif %}

# Create `ansible` user with sudo permissions and membership in `DEPLOY_GROUP`
ENV ANSIBLE_USER=ansible DEPLOY_GROUP=deployer
ENV SUDO_GROUP={{'sudo' if ('debian' in item.image or 'ubuntu' in item.image) else 'wheel' }}

ENV LANG en_US.utf8
ENV LC_ALL C.UTF-8

# Do specific actions per type of distribution
# For example for Ubuntu, generate a locate
# in addition to install a number of packages
RUN if [ $(command -v apt-get) ]; then \
    export DEBIAN_FRONTEND=noninteractive && \
    apt-get update && \
    apt-get install -y locales && \
    localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8 && \
    apt-get install --no-install-recommends -y python3 sudo bash ca-certificates iproute2 python3-apt aptitude && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*; \
  elif [ $(command -v dnf) ]; then \
    dnf makecache && \
    dnf --assumeyes install /usr/bin/python3 /usr/bin/python3-config /usr/bin/dnf-3 sudo bash iproute && \
    dnf clean all; \
  elif [ $(command -v yum) ]; then \
    yum makecache fast && \
    yum install -y /usr/bin/python /usr/bin/python2-config sudo yum-plugin-ovl bash iproute && \
    sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf && yum clean all; \
  elif [ $(command -v zypper) ]; then \
    zypper refresh && \
    zypper install -y python3 sudo bash iproute2 && zypper clean -a; \
  elif [ $(command -v apk) ]; then \
    apk update && \
    apk add --no-cache python3 sudo bash ca-certificates; \
  elif [ $(command -v xbps-install) ]; then \
    xbps-install -Syu && \
    xbps-install -y python3 sudo bash ca-certificates iproute2 && \
    xbps-remove -O; \
  fi

# Create a group and a user
RUN set -xe \
  && groupadd -r ${ANSIBLE_USER} \
  && groupadd -r ${DEPLOY_GROUP} \
  && useradd -m -g ${ANSIBLE_USER} ${ANSIBLE_USER} \
  && usermod -aG ${SUDO_GROUP} ${ANSIBLE_USER} \
  && usermod -aG ${DEPLOY_GROUP} ${ANSIBLE_USER} \
  && sed -i "/^%${SUDO_GROUP}/s/ALL\$/NOPASSWD:ALL/g" /etc/sudoers

# Remove unnecessary getty and udev targets that result in high CPU usage when using
# multiple containers with Molecule (https://github.com/ansible/molecule/issues/1104)
RUN rm -f /lib/systemd/system/systemd*udev* \
  && rm -f /lib/systemd/system/getty.target

VOLUME ["/sys/fs/cgroup", "/tmp", "/run"]
CMD ["/lib/systemd/systemd"]

