---
- name: Create tables that do not exist in nft (to avoid issues)
  ansible.builtin.command: "nft add table {{ table }}"
  become: true
  when: not table in nft_table_names
  loop: "{{ nftables_ruleset.keys() }}"
  loop_control:
    loop_var: table
  tags:
    - nftables_setup

- name: Create dynamic tables that do not exist in nft (to avoid issues)
  ansible.builtin.command: "nft add table {{ table }}"
  become: true
  when: not table in nft_table_names
  loop: "{{ nftables_dynamic_tables.keys() | list + ['inet blocklist'] }}"
  loop_control:
    loop_var: table
  tags:
    - nftables_setup
